### ISSUE TITLE
PyJWT 2.0+ compatibility

### ISSUE THREAD

**Issue by mdantonio** [fanout/pygripcontrol#5]
Hello,

gripcontrol has a dependency with PyJWT <2 that is preventing me to upgrade PyJWT in my projects.

PyJWT 2.0 has been released with some breaking changes (https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.rst) and I would like to know if you could consider a compatibility fix for PyJWT 2+

It seems to me that the only use of jwt is here:

https://github.com/fanout/pygripcontrol/blob/master/src/gripcontrol.py#L71-L75

But this code seems already compatible with the latest PyJWT versions

The same happens with pubcontrol, that should be maintained by the same team: do you prefer a similar issue in pubcontrol repository or I can extended this request to both the packages?

thank you very much for your support

**Comment by jkarneges** [comment]
Hi!

Thanks for the report. I've published pubcontrol 3.1.0 and gripcontrol 4.1.0 with support for PyJWT 2.

Let me know if you run into any issues.

**Comment by mdantonio** [comment]
Thank you very much
I can confirm that now it works fine with PyJWT 2+
